/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export * as factories from './factories'
export type { FareSpin } from './contracts/FareSpin.sol/FareSpin'
export { FareSpin__factory } from './factories/contracts/FareSpin.sol/FareSpin__factory'
export type { FareToken } from './contracts/FareToken.sol/FareToken'
export { FareToken__factory } from './factories/contracts/FareToken.sol/FareToken__factory'
export type { IFareToken } from './contracts/interfaces/IFareToken'
