/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fareSpinSol from './FareSpin.sol'
export type { fareSpinSol }
import type * as fareTokenSol from './FareToken.sol'
export type { fareTokenSol }
import type * as interfaces from './interfaces'
export type { interfaces }
